### ISSUE TITLE
get error when runing command from todoist.py

### ISSUE THREAD

**Issue by MichaelC001** [davidtkeane/todoist-cli-python-api#1]
get error when runing command from todoist.py

401 Client Error: Unauthorized for url: https://api.todoist.com/rest/v2/tasks

**Comment by davidtkeane** [comment]
> get error when runing command from todoist.py
> 
> 401 Client Error: Unauthorized for url: https://api.todoist.com/rest/v2/tasks

Hi MichaelC001!

Thanks for using my script for Todoist.  The Todoist website said the error is that the request to connect to Todoist has failed for some reason. 

Todoist website: https://developer.todoist.com/rest/v2/?python#overview
4xx	The request was processed with an error. The request was invalid and should not be retried unmodified.

1. A possibility is that the API key might be entered wrong, or the wrong API key, and could be also entered in the .env file incorrectly. Please forgive me for suggesting these options, as I don't know your level of programming, and I do not want to offend you by asking, but I had to ask, just in case.

2. There might be an issue with python modules not being installed for the script to work, but it should say this in another error when running the script, saying module not found. I will make a list of modules needed for this script to work, and add an requirements.txt file later anyway for future.

3. I will download the script on another computer and follow the steps I wrote up, getting the api key from Todoist website, adding it to the .env file, adding the endpoint or do they say rest point https://api.todoist.com/rest/v2/tasks and try and run the script on my macbook, as I wrote the script on Windows 11 using VS Code and Powershell. I will post up my findings later and hopefully, I will help fix the issue.

4. Would it possible if you could write a small journey in regards to what you did, for example.

1. I used the terminal in Kali Linux and then I entered the command $ git clone https://github.com/davidtkeane/todoist-cli-python-api.git
2. Went to Todoist website and got the api key and put it into the .env file
3. Entered the todoist folder and then python todoist.py and this is when i got the error. 

This would be really handy to know as I can improve the script for other people with your help. 

Thanks again for opening this issue and for downloading my script and giving it a go.

**Comment by davidtkeane** [comment]
Just an update. 

Running this script on my Macbook Air M1. I have had a few issues.

You will need you API key, instructions in README.md file

1. I can't list my projects I get an error and the script breaks.
2. I can create a new project I get an error and the script breaks.  But, the project does get created when you go to Todoist online.
3. I created a new file to test the Todoist API using python file.
4. I added into the Todoist test file MD file this command to test. 
$ curl -X GET \
  https://api.todoist.com/rest/v2/projects \
  -H "Authorization: Bearer 0123456789abcdef0123456789"
5. Curl works for me with no errors but when I use the python file I get a responce but not what was expected according to the Todoist website, it should have returned the same as when using curl. 
> python todoist_api_test.py
'can_assign_tasks'

I am going back to my Windows 11 machine tomorrow and check if this script works there as I made this script there.

**Comment by davidtkeane** [comment]
I just tested this curl command, just replace the api below with your own.

$ curl -X GET
https://api.todoist.com/rest/v2/tasks
-H "Authorization: Bearer 0123456789abcdef0123456789"

I was able to get back the task lists that are there.

Check if you can also, then it must be the API key could be missing a diggit or something small.

I am not sure if you get this when installing the script or when the script is running and you chose list.

I will have to fix my Macbook version first. I will then check my Windows version and have files for both in the near future.

**Comment by davidtkeane** [comment]
I am going to install the script on a new apple macbook pro m3. I will try the install and see if i get the same issue, at least find the issue that was raised for future fixes. 

1. Create a new conda env.
2. Install the git
3. I will check the machine and find the modules used and find their version, and also the version of python used in creating this script. 

Completly forgot to get back to this, but I felt that the answers I provided might have helped fix the issue, but I will do this again to double-check again.

**Comment by davidtkeane** [comment]
1. I installed the script onto a MacBook Pro m3.
2. I wrote a brand-new install script that asks for your API key and then adds it to the .env file. 
3. The problem the user had I believe and think was an error with the install_todoist.py script, when you entered the API key into the terminal, it didn't copy to the .env file. 
4. I changed the install.py file now to see if a .env file is there and if not make one.
5. when you add the key in the terminal it now goes into the .env file (I double and treble-checked this)
6. The install.py will also use the todoist_api_test.py script to check for connection and should return your projects.
7. The script will tell you if the modules are installed which ones, and which ones are not installed.
8. The install.py script will ask you to run the todoist.py which is the main file to run. 
9. I added images into the README.md file to help to see what the terminal shows.
